### ISSUE TITLE
Outdated sweet.js version

### ISSUE THREAD

**Issue by vegansk** [bopjesvla/sweet-loader#1]
Please update sweet.js version in dependencies. sweet-loader works with the latest version too.

**Comment by bopjesvla** [comment]
I haven't been using sweet.js lately so I added you as a collaborator. If you tell me your npm handle I'll give you publish access as well.

**Comment by vegansk** [comment]
Ok. https://www.npmjs.com/~vegansk

**Comment by bopjesvla** [comment]
done!
